import Head from 'next/head'

import { useEffect } from 'react';
import { useRouter } from 'next/router';
import { useAppSelector } from '../../../redux/hooks';

import AdminsLayout from '../../../src/layouts/AdminsLayout';

export default function Editor() {
    const router = useRouter();
    const { admins, admin, role } = useAppSelector(state => state.admin)

    useEffect(() => {
        if (role !== 'editor') {
            router.push('/admin');
        }
    }, [role]);

    return (
        <div>
            <Head>
                <title>Editor</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {role !== '' ?
                <AdminsLayout role={role} active='rating'>
                    editor
                </AdminsLayout>
                : ''
            }
        </div>
    )
}
