import Head from 'next/head'
import { useRouter } from 'next/router'
import { useState } from 'react'
import { Stack } from '@mui/system'
import { Button, TextField, Typography } from '@mui/material'

import { useAppDispatch, useAppSelector } from '../../redux/hooks'
import { collection, doc, onSnapshot } from "firebase/firestore";
import { db } from '../../firebase';
import { setAdmin, setAdmins, setRole } from '../../redux/slices/AdminSlice'
import { arrayBuffer } from 'stream/consumers'

export default function Login() {
    const [formErrorState, setFormErrorState] = useState(false);
    const dispatch = useAppDispatch();
    const router = useRouter()
    const { admins, admin, role } = useAppSelector(state => state.admin)

    const handleSubmit = async (event: any) => {
        event.preventDefault();
        setFormErrorState(false)

        const login = event.target[0].value;
        const password = event.target[2].value;

        await onSnapshot(doc(db, "users", login), (doc) => {
            if ((doc.id === login)) {
                if (doc.data()!.password === password) {
                    dispatch(setAdmin(doc.data()))
                    dispatch(setRole(doc.data()!.role))
                    router.push(`/admin/${doc.data()!.role}`)
                } else {
                    setFormErrorState(true)
                }
            } else {
                setFormErrorState(true)
            }
        })
    }

    return (
        <div>
            <Head>
                <title>Login</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Stack
                height='100vh'
                alignItems='center'
                justifyContent='center'
            >
                <form onSubmit={handleSubmit}>
                    <Stack
                        sx={{ padding: '20px 15px', border: '2px solid black', borderRadius: '0px 20px' }}
                        spacing={2}
                        width={400}
                    >
                        <Typography textAlign={'center'} fontSize={22}>Route Rating</Typography>
                        <TextField
                            fullWidth
                            type='login'
                            error={formErrorState}
                            id="outlined-error"
                            label="Login"
                        />
                        <TextField
                            fullWidth
                            type='password'
                            error={formErrorState}
                            id="outlined-error"
                            label="Password"
                        />
                        <Button type='submit' size='large' variant="outlined" sx={{ color: 'black', borderColor: 'black' }}>Login</Button>
                    </Stack>
                </form>
            </Stack>
        </div>
    )
}

