import Head from 'next/head'

import { useEffect, useState } from 'react';
import { useRouter } from 'next/router';
import { useAppSelector } from '../../../redux/hooks'

import AdminsLayout from '../../../src/layouts/AdminsLayout';
import Clients from '../../../src/components/Clients';

import { doc, setDoc, deleteDoc, updateDoc, collection, onSnapshot } from "firebase/firestore";
import { db } from "../../../firebase";

export default function Developer() {
    const router = useRouter();
    const { admins, admin, role } = useAppSelector(state => state.admin);
    const [clients, setClients] = useState([]);

    useEffect(() => {
        if (role !== 'developer') {
            router.push('/admin');
        }
    }, [role]);

    useEffect(() => {
        (async function () {
            await onSnapshot(collection(db, "clients"), (docs) => {
                let arr: any = [];
                docs.docs.forEach(doc => {
                    arr.push({ login: doc.id, ...doc.data() })
                })
                setClients(arr)
            });
        }());
    }, [role])

    return (
        <div>
            <Head>
                <title>Clients</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {role !== '' ?
                <AdminsLayout role={role} active='clients'>
                    <Clients clients={clients} />
                </AdminsLayout>
                : ''
            }
        </div>
    )
}
