import Head from 'next/head'

import { useEffect, useState } from 'react'
import { useRouter } from 'next/router';
import { useAppSelector } from '../../../redux/hooks'

import AdminsLayout from '../../../src/layouts/AdminsLayout';
import Posts from '../../../src/components/Posts';

import { doc, setDoc, deleteDoc, updateDoc, collection, onSnapshot } from "firebase/firestore";
import { db } from "../../../firebase";

export default function Developer() {
    const router = useRouter();
    const { admins, admin, role } = useAppSelector(state => state.admin)
    const [posts, setPosts] = useState([]);

    useEffect(() => {
        if (role !== 'developer') {
            router.push('/admin');
        }
    }, [role]);

    useEffect(() => {
        (async function () {
            await onSnapshot(collection(db, "posts"), (docs) => {
                let arr: any = [];
                docs.docs.forEach(doc => {
                    arr.push({ id: doc.id, ...doc.data() })
                })
                setPosts(arr)
            });
        }());
    }, [role])

    return (
        <div>
            <Head>
                <title>Posts</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            {role !== '' ?
                <AdminsLayout role={role} active='posts'>
                    <Posts posts={posts} />
                </AdminsLayout>
                : ''
            }
        </div>
    )
}
