import Head from 'next/head'
import { useRouter } from 'next/router'
import { doc, getDoc, updateDoc } from 'firebase/firestore';
import { db } from '../firebase';
import { useEffect } from 'react';

export default function Home() {
    const router = useRouter();

    useEffect(() => {
        if (router.query.id) {
            let dateNow = +Date.now() / 1000
            const docSnap = getDoc(doc(db, "posts", `${router.query.id}`))
                .then((docd) => {
                    if (dateNow < docd.data()!.endDate) {
                        updateDoc(doc(db, "posts", `${router.query.id}`), {
                            count: docd.data()!.count + 1
                        }).then(() => {
                            router.push(docd.data()!.originUrl)
                        })
                    }
                })
        }
    }, [router.query])

    return (
        <div className='container'>
            <Head>
                <title>Route Rating</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
        </div>
    )
}
